# Generated by Django 3.2 on 2023-04-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('orderID', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('issuedDate', models.TextField()),
                ('dueDate', models.TextField()),
                ('isSameDay', models.BooleanField()),
                ('isDelivery', models.BooleanField()),
                ('isReady', models.BooleanField()),
            ],
        ),
    ]
