# Generated by Django 3.2 on 2023-04-20 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('orderDetailID', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.TextField()),
                ('price', models.TextField()),
                ('comment', models.TextField()),
                ('orderID_ID', models.ForeignKey(db_column='orderID', on_delete=django.db.models.deletion.CASCADE, to='order.userorder')),
            ],
        ),
    ]
